centrifugal/centrifugo

- libcentrifugo/api.go
- libcentrifugo/application.go
- libcentrifugo/client.go
- libcentrifugo/handlers.go
- libcentrifugo/response.go
- libcentrifugo/response_test.go
* Remove custom marshalling of responses.
* Set error via function call.
* Remove toJson since it no longer serves any purpose.
> Clean up responses

- libcentrifugo/admin.go
- libcentrifugo/api.go
- libcentrifugo/application.go
- libcentrifugo/client.go
- libcentrifugo/commands.go
- libcentrifugo/config.go
- libcentrifugo/engine.go
- libcentrifugo/enginememory.go
- libcentrifugo/engineredis.go
- libcentrifugo/handlers.go
Some refactoring here - get rid of `interface{}` types, introduce `Message` and `ClientInfo` types, use `json` for command decoding instead of `mapstructure`, several clean ups
> Strong types

- libcentrifugo/admin.go
- libcentrifugo/application.go
- libcentrifugo/client.go
- libcentrifugo/commands.go
- libcentrifugo/config.go
- libcentrifugo/connections.go
- libcentrifugo/engine.go
- libcentrifugo/enginememory.go
- libcentrifugo/engineredis.go
- libcentrifugo/handlers.go
- libcentrifugo/hubs.go
- libcentrifugo/hubs_test.go
- libcentrifugo/structure.go
- libcentrifugo/structure_test.go
Example for Issue #12 for discussion. Just did a conversion of 4 major types. As I hope you'll agree it is very unintrusive, and later on we can change the variable names to something shorter, since the type implies what it is.
The actual name of each type is easy to change. I wasn't sure if uuid is one type, so I kept that as a string for now.
I am heading to bed now, but I can continue to work on it tomorrow.
> Add strong types for ID types.

- app.json
Consider using the secret generator so that deploys don't require know secrets.
I would provide more descriptive descriptions, but I'm not 100% sure what they should be.
> app.json suggestions

- config.go
- libcentrifugo/application.go
- libcentrifugo/config.go
- libcentrifugo/handlers.go
- libcentrifugo/handlers_test.go
- main.go
#44 
The only problem here is need to press login button in web interface as web interface does not know about `insecure_web` option turned on or off. I tried to figure out how to fix this behaviour but can't find a good way yet.
> Separate ports for API and admin, insecure web option

- libcentrifugo/application.go
- libcentrifugo/client.go
- libcentrifugo/message_test.go
- libcentrifugo/response.go
- libcentrifugo/response_test.go
> Client errors improvements

- libcentrifugo/application.go
- libcentrifugo/engine.go
- libcentrifugo/engine_test.go
- libcentrifugo/enginememory.go
- libcentrifugo/enginememory_test.go
- libcentrifugo/engineredis.go
- libcentrifugo/engineredis_test.go
> Combining publish and adding history

- libcentrifugo/client.go
Found some code that just closes client connection without sending `disconnect` without reconnect  message to it first. Fixes here.
> disconnect client without reconnect after message error

- libcentrifugo/application.go
- libcentrifugo/metrics.go
- libcentrifugo/metrics_test.go
> fix metrics races

- libcentrifugo/application.go
- libcentrifugo/engineredis.go
To be independent from client implementation, save RTT, be atomic.
> Rewrite presence methods to lua in redis engine

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/FZambia/go-sentinel/.gitignore
- Godeps/_workspace/src/github.com/FZambia/go-sentinel/LICENSE
- Godeps/_workspace/src/github.com/FZambia/go-sentinel/README.md
- Godeps/_workspace/src/github.com/FZambia/go-sentinel/sentinel.go
- libcentrifugo/engineredis.go
- libcentrifugo/engineredis_test.go
- main.go
> Sentinel support

- libcentrifugo/bytequeue/bytequeue.go
- libcentrifugo/conns/adminconn/conn.go
- libcentrifugo/conns/adminconn/conn_test.go
- libcentrifugo/conns/clientconn/conn.go
- libcentrifugo/conns/clientconn/conn_test.go
- libcentrifugo/conns/connections.go
- libcentrifugo/conns/hubs.go
- libcentrifugo/conns/hubs_test.go
- libcentrifugo/engine/enginememory/engine_test.go
- libcentrifugo/integration/integration_test.go
- libcentrifugo/node/node.go
- libcentrifugo/node/node_test.go
- libcentrifugo/proto/response.go
- libcentrifugo/server/httpserver/handlers.go
- libcentrifugo/server/httpserver/sessions.go
- libcentrifugo/server/httpserver/sessions_test.go
Here are some changes to properly handle various disconnect scenarios. Changes allow to control how to disconnect client from other parts of code using `DisconnectAdvice` struct.
> Disconnect advice

- README.md
- centrifugo.rb
- extras/scripts/homebrew.template
- extras/scripts/release.sh
```
brew tap centrifugal/centrifugo https://github.com/centrifugal/centrifugo
brew install centrifugo
```
> Homebrew formula

- README.md
To have a possibility to link to a specific readme section
> Anchors in readme

- libcentrifugo/centrifugo/main.go
Should help for process monitoring tools like Monit - see #181
> optionally create PID file

- libcentrifugo/node/cpu.go
- libcentrifugo/node/cpu_test.go
- libcentrifugo/node/node.go
> Add getrusage to get separate user/system CPU usage times

- libcentrifugo/conns/clientconn/conn.go
- libcentrifugo/engine/engineredis/engine.go
- libcentrifugo/metrics/hdrhistogram.go
- libcentrifugo/node/cpu.go
- libcentrifugo/server/handlers.go
Hi, I opened your Go Report Card and tried to fix as much as I could. Hope this helps :)
> Minor refactoring

- internal/graphite/graphite.go
Fix for broken code formatting in #233
> Redundant statement fix

- Gopkg.lock
- main.go
- vendor/github.com/centrifugal/centrifuge/README.md
- vendor/github.com/centrifugal/centrifuge/engine_redis.go
centrifuge version was updated too.
> Add support for redis TLS connection

- main.go
Adds `internal_address` option to use custom interface address for internal endpoints.
Adds `admin_external` boolean option to expose admin interface to external address (by default admin considered internal).
This solves some real life use cases.
> internal_address option,  option to expose admin to external address

- docs/content/server/private_channels.md
Add some docs to private channel section
What types of changes does your code introduce to Centrifugo? _Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply_
> add note for private channel auth

- Gopkg.lock
- vendor/golang.org/x/crypto/acme/acme.go
- vendor/golang.org/x/crypto/acme/autocert/autocert.go
- vendor/golang.org/x/crypto/acme/autocert/cache.go
- vendor/golang.org/x/crypto/acme/http.go
- vendor/golang.org/x/crypto/acme/jws.go
- vendor/golang.org/x/crypto/acme/rfc8555.go
- vendor/golang.org/x/crypto/acme/types.go
- vendor/golang.org/x/crypto/acme/version_go112.go
> Update crypto dependency

- Gopkg.lock
- config.json
- internal/admin/handlers.go
- internal/middleware/method.go
- main.go
- vendor/github.com/centrifugal/centrifuge/Gopkg.lock
- vendor/github.com/centrifugal/centrifuge/go.mod
- vendor/github.com/centrifugal/centrifuge/go.sum
- vendor/github.com/igm/sockjs-go/sockjs/handler.go
- vendor/github.com/igm/sockjs-go/sockjs/rawwebsocket.go
- vendor/github.com/igm/sockjs-go/sockjs/websocket.go
> add options to customize endpoint prefixes

- main.go
> support setting all options via env vars

- internal/middleware/log.go
> log request status code on debug log level

- main.go
> custom grpc api tls options

- Gopkg.lock
- Gopkg.toml
- internal/api/api_test.go
- internal/api/handler_test.go
- internal/middleware/auth.go
- internal/middleware/auth_test.go
- vendor/github.com/stretchr/testify/require/doc.go
- vendor/github.com/stretchr/testify/require/forward_requirements.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require.go.tmpl
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
- vendor/github.com/stretchr/testify/require/requirements.go
> Support passing api_key over URL param

- docs/content/server/authentication.md
- docs/content/server/private_channels.md
This PR is a docs only version of https://github.com/centrifugal/centrifugo/pull/326
> Doc rsa only

- docs/content/server/proxy.md
- internal/proxy/connect_http.go
- internal/proxy/http.go
- internal/proxy/options.go
- internal/proxy/refresh_http.go
- internal/proxy/rpc_http.go
- main.go
Resolves #334, more info can be found in commit docs changes.
> allow to set extra http headers to proxy, resolves #334

- docs/content/server/proxy.md
- internal/proxy/connect.go
- internal/proxy/connect_handler.go
Relates to #332, see commit docs changes for more details.
> proxy data to client, relates to #332

- internal/api/api.go
- internal/api/metrics.go
- internal/proxy/connect_handler.go
- internal/proxy/metrics.go
- internal/proxy/refresh_handler.go
- internal/proxy/rpc_handler.go
Added histograms of query durations to be able to aggregate statistics of different service replicas.
> add histograms of requests durations

- internal/proxy/http.go
> Set proxy request content-type as application/json

- docs/content/server/engines.md
- go.mod
- go.sum
- main.go
- vendor/github.com/centrifugal/centrifuge/changelog.md
- vendor/github.com/centrifugal/centrifuge/client.go
- vendor/github.com/centrifugal/centrifuge/config.go
- vendor/github.com/centrifugal/centrifuge/disconnect.go
- vendor/github.com/centrifugal/centrifuge/engine_redis.go
- vendor/github.com/centrifugal/centrifuge/errors.go
- vendor/modules.txt
Relates to #375 
```
centrifugo --engine=redis --redis_sentinels=":26379" --redis_master_name=mymaster --redis_sentinel_password=xxx
```
> Support setting Redis Sentinel password

- docs/content/server/grpc_api.md
- internal/api/grpc.go
- internal/api/grpc_test.go
- main.go
> Add grpc_api_key option

- CHANGELOG.md
- misc/release/notes.md
> v2.7.0 release notes

- docs/content/libraries/api.md
Forked the old package and updated to the current version of Laravel framework
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
> Laravel package update

- CHANGELOG.md
- docs/content/server/authentication.md
- docs/content/server/proxy.md
- internal/jwtverify/token_verifier_jwt.go
- misc/release/notes.md
What's inside:
* docs and changelog for upcoming v2.8.2
* use jwks for subscription tokens
@danikarik hello, could you please take a look?
> Use jwks for subscription tokens, notes for 2.8.2

- docs/content/blog/intro_centrifuge.md
- docs/mkdocs.yml
New post for a blog. There are still some things to do in Centrifuge library before publication: see https://github.com/centrifugal/centrifuge/pull/175
> Centrifuge intro blog post

- go.mod
- go.sum
- vendor/github.com/cristalhq/jwt/v3/README.md
- vendor/github.com/cristalhq/jwt/v3/algo.go
- vendor/github.com/cristalhq/jwt/v3/algo_eddsa.go
- vendor/github.com/cristalhq/jwt/v3/algo_es.go
- vendor/github.com/cristalhq/jwt/v3/algo_hs.go
- vendor/github.com/cristalhq/jwt/v3/algo_ps.go
- vendor/github.com/cristalhq/jwt/v3/algo_rs.go
- vendor/github.com/cristalhq/jwt/v3/build.go
- vendor/github.com/cristalhq/jwt/v3/claims.go
- vendor/github.com/cristalhq/jwt/v3/numeric_date.go
- vendor/github.com/cristalhq/jwt/v3/parse.go
- vendor/modules.txt
> update cristalhq/jwt to 3.0.9

- internal/client/handler.go
> Fix panic when user_subscribe_to_personal is on (fixes #436)

- docs/content/server/proxy.md
- internal/proxy/publish.go
- internal/proxy/publish_handler.go
> Publish proxy data modify

- internal/client/handler_test.go
- internal/proxy/connect_handler_test.go
- internal/tools/test_helpers.go
add tests for connect handler + transfer some common tests dependencies into `tools` package
> Connect handler tests (proxy package)

- internal/proxy/connect_handler_test.go
- internal/proxy/publish_handler_test.go
> Publish handler tests (proxy package)

- internal/proxy/refresh_handler_test.go
> Refresh handler tests (proxy package)

- internal/proxy/subscribe_handler_test.go
add tests for subscribe handler
> Subscribe handler tests (proxy package)

- internal/proxy/publish_handler.go
- internal/proxy/publish_handler_test.go
- internal/proxy/refresh_handler.go
- internal/proxy/refresh_handler_test.go
- internal/proxy/rpc_handler.go
- internal/proxy/rpc_handler_test.go
- internal/proxy/subscribe_handler.go
- internal/proxy/subscribe_handler_test.go
- internal/proxy/test_grpc_server.go
Add tests for joint http/grpc publish handlers.
Also upd publish handler on context done.
> Tests for http and grpc publish handlers

- internal/proxy/rpc_handler_test.go
- internal/proxy/test_grpc_server.go
Added tests for joint testing http/grpc rpc handlers.
> Tests for http and grpc rpc handlers

- internal/proxy/subscribe_handler_test.go
- internal/proxy/test_grpc_server.go
Added tests for joint testing http/grpc subscribe handler.
> Tests for http and grpc subscribe handler

- .github/workflows/release.yml
- .github/workflows/test.yml
Use recent Go release for builds and tests
> Use go 1.17.1

- go.mod
- go.sum
- internal/tools/address.go
- internal/tools/config.go
- internal/tools/duration.go
- main.go
> Report line and column for JSON config file syntax error

- .github/workflows/test.yml
Fixes Golang-ci lint action failure - https://github.com/centrifugal/centrifugo/runs/5870325083?check_suite_focus=true
> fix golang-ci lint action

- main.go
> Fix top-level granular subscribe and publish proxies

- Makefile
> Support Debian bullseye, drop jessie

- main.go
> Add api_external option, fixes #536

- internal/natsbroker/broker.go
We can avoid double encoding of messages published to Nats by using the client protocol v2 push format. Thus saving one alloc. The format of the messages we publish is an internal implementation detail, so we can change it.
Before:
```
BenchmarkNatsEnginePublish-12              	 3881850	       296.7 ns/op	      56 B/op	       2 allocs/op
BenchmarkNatsEnginePublishParallel-12      	 3006904	       416.1 ns/op	      56 B/op	       2 allocs/op
```
After (-1 alloc)
```
BenchmarkNatsEnginePublish-12              	 4523809	       254.9 ns/op	      32 B/op	       1 allocs/op
BenchmarkNatsEnginePublishParallel-12      	 3242451	       363.9 ns/op	      32 B/op	       1 allocs/op
``` 
Also, will be slightly faster on message unmarshaling when receiving it from PUB/SUB.
> Nats: use push format from client protocol v2

- internal/unihttpstream/config.go
- internal/unihttpstream/handler.go
- internal/unihttpstream/transport.go
- internal/unisse/config.go
- internal/unisse/handler.go
- internal/unisse/transport.go
- internal/uniws/config.go
- internal/uniws/handler.go
- internal/uniws/transport.go
- internal/wt/config.go
- internal/wt/handler.go
- internal/wt/transport.go
- main.go
> Configure server-to-client ping/pong intervals

- .github/workflows/release.yml
- .github/workflows/test.yml
Up Go version for tests and build
> Use go 1.19.2

- internal/client/handler.go
> Process client channels for no-credentials case also

- internal/tools/tls.go
- main.go
> Extend TLS configuration

- internal/unihttpstream/handler.go
- internal/unisse/handler.go
Analogue of https://github.com/centrifugal/centrifuge/pull/292
> Use response controller in uni SSE and HTTP-streaming handlers

- Makefile
Create centrifugo packages for ubuntu jammy
> Add support for ubuntu jammy

- Makefile
> Drop packaging for ubuntu xenial

- go.mod
- go.sum
- internal/middleware/auth.go
- internal/middleware/auth_test.go
- internal/middleware/connlimit.go
- internal/middleware/connlimit_test.go
- internal/middleware/cors.go
- internal/middleware/headers.go
- internal/middleware/log.go
- internal/middleware/method.go
- main.go
Simplify route configuration by chaining middlewares.
> Chain middlewares with alice

- go.mod
- go.sum
- internal/proxy/unknown_keys.go
- internal/rule/unknown_keys.go
- internal/tools/unknown_keys.go
- main.go
> Warn about unknown config keys

- CHANGELOG.md
- misc/release/notes.md
> Prepare v5.0.2 release

- go.mod
- go.sum
- internal/telemetry/provider.go
Adding support for gRPC otlp exporter
> feat: Add GRPC tracing

- internal/jwtverify/token_verifier_jwt.go
- internal/jwtverify/token_verifier_jwt_test.go
test: new JWKS tests for RSA and EC
Fixes #719
> feat: support for EC keys in JWK sets and EC JWTs when using JWKS

- CHANGELOG.md
- misc/release/notes.md
Some useful improvements, performance tweaks, and the fix of Redis reversed history.
> Release notes for Centrifugo v5.1.1

- internal/rule/rule.go
- internal/rule/rule_test.go
> Fix nil pointer dereference upon channel regex check inside namespace

- internal/admin/handlers.go
Instead of relying on different heuristics for understanding enabled insecure admin mode and detecting server edition we now have settings endpoint called on start.
Also embedded admin UI which supports these changes was updated here.
Some other improvements in admin UI:
* Not calling info API periodically on status page when window is not visible (using visibility browser API)
* Red login button
* Support for SSO auth over OpenID Connect (for Centrifugo PRO)
> Admin settings endpoint and updated admin ui

- internal/jwtverify/token_verifier_jwt.go
- internal/jwtverify/token_verifier_jwt_test.go
> Support for OKP JWKs based on Ed25519

- .github/workflows/release.yml
- .github/workflows/test.yml
- misc/release/notes.md
Release notes for the upcoming Centrifugo v5.2.1
> Release notes for Centrifugo v5.2.1

- internal/jwtverify/token_verifier_jwt.go
> Better error message for invalid connection token with channel claim

- .github/workflows/release.yml
- .github/workflows/test.yml
- misc/release/notes.md
> v5.3.1 release notes, use go1.22.2

- internal/tools/tls.go
> chore: fix function names in comment

- misc/release/notes.md
Preparations for v5.3.3 release.
> Release notes for 5.3.3

- Makefile
> Support release for Debian 12 Bookworm

- internal/consuming/consuming.go
Use proper mapstructure and JSON tags.
> Fix disabling consumer

- internal/jwtverify/token_verifier_jwt.go
More descriptive error messages during connection and subscription token checks. Relates #837
> More descriptive JWT check error messages

- internal/client/handler.go
> Fix permission check for clients already passed subscribe checks

- internal/client/handler.go
> Use errors.Is for token expired error checks

- go.mod
- go.sum
- misc/release/notes.md
Release notes for upcoming v5.4.3
> Prepare v5.4.3 release notes

- internal/proxy/connect_handler.go
> Process connect proxy result subs

- misc/release/notes.md
> Release notes for v5.4.5

- .github/workflows/release.yml
- .github/workflows/test.yml
- go.mod
> Up go versions (Go 1.23)

- internal/sockjs/handler_sockjs.go
- internal/unigrpc/grpc.go
- internal/unihttpstream/handler.go
- internal/unisse/handler.go
- internal/uniws/handler.go
- internal/wt/handler.go
- misc/release/notes.md
> Release notes for Centrifugo v5.4.6

- go.mod
- go.sum
Updating Quic and WebTransport dependencies.
> Up quic and webtransport deps

- internal/consuming/kafka.go
> Support Kafka scram-sha-256, scram-sha-512 and aws-msk-iam SASL

- Dockerfile
- go.sum
- misc/release/notes.md
Preparing release notes for Centrifugo v5.4.9
> Prepare v5.4.9 release notes

- misc/release/notes.md
> v6 release notes

- misc/release/notes.md
Preparing v6.0.2 release here.
> Prepare release notes for v6.0.2

- Makefile
Relates #946 
Also removing ubuntu/bionic due to EOL date passed
> Add ubuntu/noble, remove ubuntu/bionic

- misc/release/notes.md
> Release notes for v6.1.0

- internal/natsbroker/broker.go
- internal/natsbroker/broker_test.go
> Apply channel replacements in nats raw mode publish

- internal/api/consuming.go
- internal/api/consuming_test.go
- internal/cli/configdoc/schema.json
- internal/config/validate.go
- internal/configtypes/types.go
- internal/consuming/consuming.go
Various tweaks for huge async consumers update coming in [v6.2.0](https://github.com/centrifugal/centrifugo/pull/976)
> Consumers: validation, comments, config defaults, some refactoring

- Procfile
Was used for Heroku. But these days we are not providing built-in Heroku integration and Procfile is not even correct due to changes in v6.
> Remove Procfile

- internal/app/engine.go
> Fix log entries

- internal/cli/configdoc/schema.json
- internal/configtypes/types.go
- internal/natsbroker/broker_test.go
Clearer separation analogous to Redis Broker.
> Nats config types refactoring

- misc/release/notes.md
Release notes for upcoming Centrifugo v6.2.3
> Prepare v6.2.3 release notes

- internal/cli/configdoc/schema.json
> Regenerate config schema with latest options

- .github/workflows/test.yml
- CHANGELOG.md
- _typos.toml
- internal/api/api.go
- internal/apiproto/swagger/api.swagger.json
- internal/cli/configdoc.go
- internal/cli/configdoc/schema.json
- internal/config/config.go
- internal/config/envconfig/envconfig_1.8_test.go
- internal/config/envconfig/envconfig_test.go
- internal/configtypes/redis.go
- internal/consuming/postgresql.go
- internal/consuming/readme.md
- internal/survey/survey.go
- internal/websocket/server_test.go
This PR mainly introduces typos for spell checking and fixes some typos
> Introduce typo check & fix typos

- internal/consuming/kafka_test.go
Fixes:
```
=== RUN   TestUnboundedQueue_ConcurrentSafety
kafka_test.go:1005:
Error Trace:	/Users/alexander.emelin/centrifugal/centrifugo/internal/consuming/kafka_test.go:1005
Error:      	Not equal:
expected: 1000
actual  : 876
Test:       	TestUnboundedQueue_ConcurrentSafety
```
> Fix flaky Kafka test

- internal/app/run.go
- internal/usage/usage.go
A bit unfortunate, since did not allow to understand the usage when we were curious..
> Fix missing webtransport in usage stats
