libcentrifugo/auth/auth.go
Use hmac.Equal to compare tokens in constant time to avoid timing attacks.
=> auth: use constant-time comparison

libcentrifugo/admin.go, libcentrifugo/admin_test.go, libcentrifugo/api.go, libcentrifugo/application.go, libcentrifugo/client.go, libcentrifugo/config.go, libcentrifugo/connections.go, libcentrifugo/engine.go, libcentrifugo/enginememory.go, libcentrifugo/engineredis.go, libcentrifugo/handlers.go, libcentrifugo/hubs.go, libcentrifugo/hubs_test.go, libcentrifugo/structure.go, libcentrifugo/structure_test.go
I have gone through the project, and changed many of the names to a more go idiomatic form.
See for instance [What's in a name?](http://talks.golang.org/2014/names.slide#1). I guess a lot comes from the python heritage.
Most of what I have changed:
* Avoid 'get', 'set', 'handle' prefixes where it makes sense.
* Shorten a few types `Connection` -> `Conn`, `Command` -> `Cmd`, 
* Change some member variables to shorter versions.
I haven't done anything to local variables or exported functions.
I can see it no longer merges, but i can of course re-base if you don't object to the idea.
=> Rename a whole bunch of funtions to a shorter version.

libcentrifugo/api.go, libcentrifugo/api_test.go
Fix 'err' being shadowed, so the error returned from the API command was being ignored.
Also add empty params to test, so Unmarshal doesn't fail.
=> Fix unintentional shadowing

libcentrifugo/application_test.go, libcentrifugo/hubs_test.go
Benchmarks the raw SubHub performance as well as client routing performance.
Right now it will usually crash with internal server error until #19 and #23 is fixed.
=> Add very rough benchmarks

libcentrifugo/centrifugo.go, libcentrifugo/client.go, libcentrifugo/config.go, libcentrifugo/errors.go, libcentrifugo/handlers.go, libcentrifugo/queue.go, libcentrifugo/stringqueue/stringqueue.go
but instead disconnect users if it takes too long to send a message.
Continuation of #19.
TODO:
*  Hook up with #18 when this is merged.
=> No limit on the message queue size, 

CHANGELOG.md, main.go
New flags:
```
--ssl                   - indicates ssl should be used.
--ssl_cert="file.cert"  - path to X509 certificate file.
--ssl_key="file.key"    - path to X509 certificate key.
```
For #27
=> Add TLS support. 

libcentrifugo/api.go, libcentrifugo/application.go, libcentrifugo/application_test.go, libcentrifugo/body.go, libcentrifugo/engine.go, libcentrifugo/engine_test.go, libcentrifugo/enginememory.go, libcentrifugo/enginememory_test.go, libcentrifugo/engineredis.go, libcentrifugo/engineredis_test.go, libcentrifugo/handlers.go
New server API command implemented here. It's called `channels` and returns all active (with one or more subscribers) channels in project at moment. It's not available for client, just for API calls.
This change required to add new method to `Engine` interface.
It works with Memory and Redis engines. But for Redis Engine it requires Redis >= 2.8.0 (http://redis.io/commands/pubsub)
=> Channels command

config.go, libcentrifugo/application.go, libcentrifugo/application_test.go, libcentrifugo/config.go, libcentrifugo/engine.go, libcentrifugo/engine_test.go, libcentrifugo/enginememory.go, libcentrifugo/enginememory_test.go, libcentrifugo/engineredis.go, libcentrifugo/engineredis_test.go, libcentrifugo/hubs.go, libcentrifugo/hubs_test.go, main.go
See design discussion on #50 for details.
This is tested to match the guarantees documented there.
Note this is optional and opt-in only.
I've tested the config changes locally and tested that you can opt in on a namespace and have the desired behaviour.
=> Only store active (Fixes #50)

libcentrifugo/engineredis.go, libcentrifugo/engineredis_test.go, main.go
As always, I'm not in love with many of the names I choose. I've opted to balance clarity and previty with shortened words but being clear about the semantics... but I'm open to suggestions.
I have this branch running now with ~5k messages a second being published and no queue backlog (with 16 shards).
Obviously we will need to document all these new features in the book once we prepare 1.3 release - @FZambia how do you normally do that? Wait until 1.3 features are final and then update it?
I also considered making the new publish more separate from the "old" api, and also considered only supporting publish/broadcast methods on it with simpler syntax but it ened up just being a lot more code complication for not much benefit.
Finally, I'm not really very pleased with the test suite for …
=> Implement sharded publish queues for redis engine to improve throughput. Refs #52

libcentrifugo/engineredis.go, libcentrifugo/engineredis_test.go, main.go
Fixes #54
Tests pass (after fixing them).
Tested in production with 50k active users and this fixed all the errors I saw at load - been running for an hour now with nearly a million connections made in that time and 0 fatal disconnects.
=> Racey redis

libcentrifugo/metrics.go, libcentrifugo/metrics_test.go
Also cleans up cruft from recent back and forth on metrics code.
Adds comments to hopefully ensure we don't screw up counter alignment again...
- new benchmark added to proove value of padding to cache line
- all test pass again
- Metrics remains backwards compatible for `gocent` and JSON output
- built with `-race` and ran 100 concurrent API requests for 30 seconds several times, no races
- left running past several `NodeMetricsInterval`s and no races on Update
- `go vet` doesn't complain about anything related to this change (minor complaints can be dealt with in another diff).
I realised last night that I also ignored false-sharing issues with atomics - since we pack `metricsCounter` into contiguous memory, and each is only 24 bytes, up to 3 `value` fields will be in each 64byte cache …
=> Fix dependence on Mutex implementation for alignment of atomics

libcentrifugo/api.go, libcentrifugo/application.go, libcentrifugo/engine.go, libcentrifugo/engine_test.go, libcentrifugo/enginememory.go, libcentrifugo/enginememory_test.go, libcentrifugo/engineredis.go, libcentrifugo/engineredis_test.go
=> Publish batching in Redis Engine

main.go
Use new SockJS version. Note that to use iframe-based SockJS transports server and client SockJS versions must be the same so some applications need to update there client-side SockJS version (or set `sockjs_url` option to use old library version).
=> use SockJS 1.1 by default

libcentrifugo/application.go, libcentrifugo/client.go, libcentrifugo/handlers.go, libcentrifugo/hdrhistogram/hdrhistogram.go, libcentrifugo/hdrhistogram/hdrhistogram_test.go, libcentrifugo/metrics.go, libcentrifugo/metrics_test.go, vendor/github.com/codahale/hdrhistogram/LICENSE, vendor/github.com/codahale/hdrhistogram/README.md, vendor/github.com/codahale/hdrhistogram/hdr.go, vendor/github.com/codahale/hdrhistogram/window.go, vendor/vendor.json
Here is first (without tests yet) implementation of latencies for HTTP API response times and client API response times. I am planning to finish this soon - here just showing first concept.
There are some caveats - for example we include latencies for different types of methods (publish, broadcast, presence etc) into one histogram. It's rather hard to separate these all into different histograms. Maybe if we had different API handlers for all methods it would be more logical. But anyway those resulting numbers can be useful for monitoring.
Also I should still think about proper synchronization.
Example of stats:
```json
{
"uid": "2",
"method": "stats",
"error": null,
"body": {
"data": {
"nodes": [
{
"uid": "918600b0-69e8-4380-8d86-644e4eb9068b",
"name": "MacAir.local_8000", …
```
=> latencies for http api responses and client api responses

libcentrifugo/application.go, vendor/github.com/FZambia/go-logger/LICENSE, vendor/github.com/FZambia/go-logger/README.md, vendor/github.com/FZambia/go-logger/logger.go, vendor/vendor.json
Added TRACE logging of messages coming to node: admin, client message, join message, leave message. That was not so easy as TRACE logging allocated a lot even if the actual log level was higher. I updated logger library and now TRACE logging lines do not affect performance.
=> Message trace logs

libcentrifugo/centrifugo/main.go, libcentrifugo/conns/clientconn/conn.go, libcentrifugo/conns/clientconn/conn_test.go, libcentrifugo/node/config.go, libcentrifugo/proto/commands.go, libcentrifugo/proto/response.go, libcentrifugo/server/httpserver/handlers.go
As we are going to send automatic pings from clients to server here are some simple changes to close idle clients. At moment client must explicitly set `"ping": true` in `connect` command to enable idle check.
Also this pr includes several changes to make client--server protocol more readable and a bit more compact.
=> Support for client side ping

libcentrifugo/server/httpserver/config.go, libcentrifugo/server/httpserver/handlers.go, libcentrifugo/server/httpserver/server.go, vendor/vendor.json
Option to enable `permessage-deflate` compression for raw websocket connections: `websocket_compression`. See #115
=> Raw websocket compression support

libcentrifugo/engine/enginememory/engine.go, libcentrifugo/engine/enginememory/engine_test.go, libcentrifugo/engine/engineredis/engine.go, libcentrifugo/engine/engineredis/engine_test.go
Attempt to resolve `history_drop_inactive` edge case described in #50 
Surprisingly it seems that it's enough to touch history for a `lifetime` period only on `unsubscribe` event. After `subscribe` we have at least one subscriber so we will push into history anyway. 
For memory engine I've added explicit method to `touch` history. For Redis engine new `touch` key with TTL was introduced. Originally I thought to just touch existing history list key - but due to how Redis works it's impossible as list key does not exist when there are no items in list (and I have not found a way to create empty list).
=> Resolve history drop inactive edge case

libcentrifugo/engine/engineredis/engine.go
When node subscribed on many channels and Redis disconnects - it's possible that node does not restore it's subscribing state after reconnecting to Redis. Including control channels. This leads to situation where some nodes become isolated from PUB/SUB. Here is patch for this.
=> Fix mass resubscribe

libcentrifugo/api/v1/api_test.go, libcentrifugo/channel/channel.go, libcentrifugo/conns/adminconn/conn_test.go, libcentrifugo/conns/clientconn/conn_test.go, libcentrifugo/engine/engine.go, libcentrifugo/engine/enginememory/engine.go, libcentrifugo/engine/enginememory/engine_test.go, libcentrifugo/engine/engineredis/engine.go, libcentrifugo/engine/engineredis/engine_test.go, libcentrifugo/integration/integration_test.go, libcentrifugo/node/config.go, libcentrifugo/node/config_test.go, libcentrifugo/node/node.go, libcentrifugo/node/node_test.go, libcentrifugo/server/httpserver/handlers_test.go
Made some layout refactor to move channel specifics to separate package. @banks what do you think? My main idea was to isolate channel opts from proto package because we can't make channel options part of protocol anyway - this is stable part of Centrifugo and does not depend on request/response message format.
=> Channel package to isolate channel options from proto

libcentrifugo/conns/hubs.go
This will allow to reliably unsubscribe clients when sending unsubscribe command via HTTP API. All unsubscribe events will be fired on client side anyway as soon as client disconnected - so actually that was unnecessary step.
=> do not send unsubscribe on shutdown

.goreleaser.yml, .travis.yml, Dockerfile
Simplify release workflow using [goreleaser](https://github.com/goreleaser/goreleaser).
Build with `-s -w` flags to minify output file.
Use alpine:3.7 as FROM Docker image.
Fixes #197
Signed-off-by: Artemiy Ryabinkov <getlag@ya.ru>
=> Use goreleaser to release.

CHANGELOG.md, docs/content/deploy/docker.md, docs/content/server/admin.md, docs/content/transports/sockjs.md, internal/api/api.go, internal/api/grpc.go, internal/api/unmarshal.go, internal/graphite/graphite.go, main.go
I have fixed a couple of typos in comments, READMEs and variable names. However, there was typo in a the following line of code - ...WithLabelValues(h.protocol, "unsibscribe")... where "unsubscribe" was incorrectly spelled. This can be a problem if metrics label names are incorrectly spelled, so it might be a good idea to put those names in a separate const ( ... ) space.
=> Fixed typos and metrics name

internal/health/health.go, main.go
This pr contains skeleton to support heal check endpoint in Centrifugo as requested in #252 
To finish this `Health()` method should be added to `Centrifuge` library. More details in https://github.com/centrifugal/centrifuge/issues/27
=> Skeleton to support healthcheck endpoint

docs/content/deploy/tuning.md
Existing link redirects to generic Riak documentation, so fixed reference to proper page.
=> Corrected reference to riak documentation

.travis.yml, misc/scripts/package.sh
Use default compression algorithms instead of `bzip2` broken in fpm 1.11.0
Fixes #275
=> Fix building deb packages with fpm

Gopkg.lock, main.go, vendor/golang.org/x/crypto/acme/acme.go, vendor/golang.org/x/crypto/acme/autocert/autocert.go, vendor/golang.org/x/crypto/acme/autocert/cache.go, vendor/golang.org/x/crypto/acme/autocert/listener.go, vendor/golang.org/x/crypto/acme/autocert/renewal.go, vendor/golang.org/x/crypto/acme/http.go, vendor/golang.org/x/crypto/acme/jws.go, vendor/golang.org/x/crypto/acme/types.go
=> Support acme tls-alpn-01 challenge

Gopkg.lock, main.go, vendor/github.com/centrifugal/centrifuge/.travis.yml, vendor/github.com/centrifugal/centrifuge/handler_sockjs.go
v2.2.3 introduced regression in SockJS WebSocket transport: cross-domain requests were prohibited while in previous version we allowed to work cross-domain. This fixes a regression.
=> Fix v2.2.3 sockjs websocket regression for cross domain requests

config.json, internal/jwt/jwt.go, main.go, vendor/github.com/rs/zerolog/go.mod
This pull request adds support for JWT with RSA algorithm. Previously Centrifugo only worked with HMAC tokens.
Added new option `token_rsa_public_key` which is a public key string in PEM format.
`secret` option is deprecated and will be removed in next major release if it happens (Centrifugo v3, not even planned yet). We suggest to use `token_hmac_secret_key` instead which is much more meaningful.
=> Support RSA tokens

docs/content/libraries/api.md
I developed a bundle for PHP-framework Symfony [https://github.com/fre5h/CentrifugoBundle](https://github.com/fre5h/CentrifugoBundle) and want to add a link in Centrifugo docs. So PHP-developers can find it, if they want to integrate Centrifugo into Symfony applications.
=> Add CentrifugoBundle for Symfony framework to the list of HTTP API client

main.go
Allow writing for a process user only. Maybe should be 0600, but I think 0644 is tolerable for Centrifugo and should not break existing setups.
=> Stricter log file perm

docs/content/server/authentication.md, docs/content/server/private_channels.md
Pull request where support added: #420
=> Docs for ECDSA

.github/workflows/test.yml
Otherwise `actions/setup-go@v2` action uses 1.15.6
=> Use go 1.15.7 for tests

.github/workflows/release.yml, .goreleaser.yml
currently add support for amd64 and arm64
=> [feature] support multi arch

docs/content/server/configuration.md
"websocket_message_size_limit"
This configuration is missing on documents.
=> [DOC] websocket_message_size_limit

internal/api/handler.go, internal/health/health_test.go, internal/jwks/manager.go, internal/proxy/http.go, internal/tools/config.go, main.go
in Go 1.16 [ioutil](https://golang.org/pkg/io/ioutil) became deprecated ([release notes 1.16](https://golang.org/doc/go1.16#ioutil)) I think migrate to io.
=> migrate from ioutil to io, os.

internal/proxy/connect_handler_test.go, internal/proxy/publish_handler_test.go, internal/proxy/refresh_handler_test.go, internal/proxy/test_grpc_server.go, internal/tools/test_helpers.go
Added tests for joint testing http/grpc refresh handlers.
Also refactored connect/publish handlers to reduce code duplication and improve readability
https://github.com/centrifugal/centrifugo/commit/f756155939446588dee88227a8dc81a24f755de3
=> Tests for http and grpc refresh handlers

internal/jwtverify/token_verifier.go, internal/jwtverify/token_verifier_jwt.go, internal/jwtverify/token_verifier_jwt_test.go, main.go
Two new string options `token_issuer` and `token_audience` which when set will enable [aud](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3) and [iss](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1) JWT checks.
=> Support checking token aud and iss claims

.github/workflows/release.yml, .goreleaser.yml, internal/build/build.go, internal/notify/notify.go, internal/rule/rule.go, internal/tntengine/multi_conn.go, internal/usage/metric.go, internal/usage/usage.go, internal/usage/usage_test.go, main.go, misc/scripts/package.sh
This pr allows collecting anonymous Centrifugo usage stats.
Important things:
* We send stats once in 24 hours
* Data is impersonal – no ip, hostname, any identifiers are sent.  Only impersonal counters to estimate installation size distribution and feature use.
* Enabled by default, possible to disable using `"anonymous_stats_disable": true`.
=> Sending anonymous usage stats

misc/packaging/centrifugo.service
Fixes warning:
```
/lib/systemd/system/centrifugo.service:22: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
```
This is now equivalent to StandardOutput=journal, and recent versions of systemd log a warning for it. Instead of updating it to journal, remove it: the default if not specified is to respect the DefaultStandardOutput setting from /etc/systemd/system.conf, which in turn defaults to journal.
Also, syslog.target is deprecated.
=> Update systemd service

go.mod, go.sum, main.go
Automatically set `GOMAXPROCS` to match Linux container CPU quota. 
And since Go 1.5, `GOMAXPROCS` defaults to `runtime.NumCPU()`, so no need to call `runtime.GOMAXPROCS(runtime.NumCPU())` actually.
=> Use go.uber.org/automaxprocs to set GOMAXPROCS

internal/client/handler.go, internal/middleware/connlimit.go, internal/rule/rule.go, main.go
Add an integer option `client_connection_limit` that (when set to a value > 0) limits the max number of connections single Centrifugo node can handle. It acts on HTTP middleware level and stops processing request if the condition met. It logs a warning into logs in this case and increments `centrifugo_node_client_connection_limit` Prometheus counter. Client SDKs will attempt reconnecting.
Relates #544
=> Client connection limit

internal/client/client.go, internal/client/handler.go, internal/client/handler_test.go, internal/proxy/client.go, internal/proxy/publish_handler.go, internal/proxy/refresh_handler.go, internal/proxy/rpc_handler.go, internal/proxy/subscribe_handler.go, internal/tools/test_helpers.go
According to subscribe proxy docs:
> Subscribe proxy does not proxy private and user-limited channels at the moment.
This worked in v3, but in Centrifugo v4 this behaviour is broken, Centrifugo proxies user-limited channels also. This PR fixes this.
=> Avoid proxying user limited channel

.gitignore, internal/proxy/grpc.go, internal/proxy/http.go, main.go
Hi!
Headers config in proxies should be case-insensitive because in the [RFC](https://www.rfc-editor.org/rfc/rfc9110.html#name-header-fields) they are. 
Current flow can lead to some bugs, ex. when you set `Authorization` header in the config, but your client sends it like `authorization`
=> Headers are now fully in lowercase

internal/admin/handlers.go, internal/reverseproxy/proxy.go, main.go
This will allow running admin web UI app in development mode and serve it with Centrifugo – inheriting UI auto-reload feature. So we can serve UI without `dist` folder requirement.
=> Reverse proxy to admin web UI app

main.go
Relates #572 
Here we lowercase headers in granular proxies to inherit logic added in #558
=> Fix insensitive case match for granular proxy headers

internal/api/api.go, internal/client/handler.go, internal/jwtverify/token_verifier_jwt.go, internal/proxy/connect_handler.go, internal/proxy/publish_handler.go, internal/proxy/subscribe_handler.go, internal/rule/namespace.go, main.go
This introduces a duration option `history_meta_ttl` for channel namespace.
Global meta TTL can be set over `default_history_meta_ttl` duration option (it's 90 days if not explicitly set).
Also renamed `presence_ttl` to `default_presence_ttl` – seems at some point in the future we may want making presence TTL configurable on namespace level also.
Relates #599
=> Per namespace history_meta_ttl

Makefile, internal/apiproto/api.proto, internal/apiproto/api.swagger.json, internal/apiproto/api.swagger.proto, internal/apiproto/generate_swagger.sh, internal/apiproto/google/api/annotations.proto, internal/apiproto/google/api/http.proto, internal/apiproto/protoc-gen-openapiv2/options/annotations.proto, internal/apiproto/protoc-gen-openapiv2/options/openapiv2.proto, internal/apiproto/readme.md, internal/middleware/auth.go, internal/middleware/auth_test.go, main.go, misc/scripts/generate.sh, misc/scripts/update_swagger_web.sh, misc/scripts/update_web.sh
Generate Open API 2.0 schema from Protobuf definitions. Using separate .proto file to keep our main one clean. Optionally serve Swagger UI on `/swagger` path (when `"swagger": true`).
Having Open API spec will also allow generating API clients for Centrifugo v5 new HTTP API using [swagger-codegen](https://swagger.io/tools/swagger-codegen/) or similar tools.
TODO:
https://user-images.githubusercontent.com/1196565/224783497-ccd34ae0-4a61-4218-9325-afa47500430a.mov
=> Swagger spec generation

go.mod, go.sum, internal/cli/token.go, internal/client/handler_test.go, internal/jwks/manager.go, internal/jwks/manager_test.go, internal/jwtverify/token_verifier_jwt.go, internal/jwtverify/token_verifier_jwt_test.go, main.go
More generic version of #618 
It's possible to extract vars from issuer and aud JWT claims using Go regexp named groups, then use these vars to construct JWKS endpoint dynamically. In this case JWKS endpoint may be set in config as template. Let's look how this may help in case of using different realms of Keycloak:
```json
{
"token_issuer_regex": "https://example.com/auth/realms/(?P<realm>[A-z]+)",
"token_jwks_public_endpoint": "https://keycloak:443/{{realm}}/protocol/openid-connect/certs"
}
```
Two new options introduced:
* `token_issuer_regex` - match JWT issuer against this regex, extract named groups to variables for jwks endpoint construction.
* `token_audience_regex` - match JWT audience against this regex, extract named groups to variables for jwks endpoint construction.
TODO:
=> Dynamic jwks based on iss and aud

.github/workflows/release.yml, Makefile, misc/scripts/package.sh
Relates #644 
Also do not use `gox` for the build - just use `go`.
=> Disable CGO in rpm/deb Centrifugo build

internal/client/handler.go, internal/client/handler_test.go, main.go
Relates #640 
Enables a way to use separate configuration for subscription tokens. When `separate_subscription_token_config` is true then Centrifugo does not look at general token options at all when verifying subscription tokens and uses config options starting from `subscription_token_` prefix instead.
```json
{
"token_jwks_public_endpoint": "https://localhost:8080/realms/protocol/openid-connect/certs",
"separate_subscription_token_config": true,
"subscription_token_hmac_secret_key": "some_strong_secret"
}
```
=> Separate subscription token config

internal/cli/token.go, main.go
Adding possibility to create non-expiring tokens:
```
./centrifugo gentoken -t -1
```
And suppress all the output except token itself (may be useful for development automation):
```
./centrifugo gentoken -q
```
=> Quiet mode and no expiration for gentoken/gensubtoken cli commands

internal/proxy/connect_handler_test.go, internal/proxy/grpc.go, internal/proxy/http.go, internal/proxy/proxy.go, internal/tools/config.go, internal/tools/unknown_keys.go, main.go
Relates #684
`proxy_static_http_headers` is a set of key/value pairs to attach to HTTP proxy requests as headers. Headers received from HTTP client request or metadata from GRPC client request both have priority over values set in this map.
```json
{
...
"proxy_static_http_headers": {
"X-Custom-Header": "custom value"
}
}
```
Also added `static_http_headers` key for granular proxy configuration.
=> Add proxy_static_http_headers option and static_http_headers key for granular proxy

internal/proxy/subscribe_handler.go
Adds missing support for `expire_at` field from subscribe proxy result.
Addresses this comment: https://github.com/centrifugal/centrifugo/issues/706#issuecomment-1722196878
=> Support expire_at of SubscribeResult

internal/cli/token.go, internal/client/handler.go, internal/jwtverify/token_verifier.go, internal/jwtverify/token_verifier_jwt.go, internal/jwtverify/token_verifier_jwt_test.go, internal/rule/rule.go, main.go
Adding boolean option `client_insecure_skip_token_signature_verify`
If enabled tells Centrifugo to skip JWT signature verification - for both connection and subscription tokens. **This is insecure and should only be used for development and testing purposes.** Token claims are parsed as usual - so token should still follow JWT format.
=> Option to skip client token signature verification 

.github/workflows/release.yml, .github/workflows/test.yml, CHANGELOG.md, misc/release/notes.md
We are approaching to Centrifugo v5.1.0. Here is a PR which adds release notes and makes final preparations for the release.
=> Prepare v5.1.0 release notes

.github/workflows/test.yml
Use go 1.21.x and up golangci-lint to the latest version
=> Up golangci-lint to v1.54.2

internal/client/handler.go, internal/rule/cache.go, internal/rule/cache_test.go, internal/rule/rule.go, internal/rule/rule_test.go, main.go
Using `atomic.Value` to avoid config locks, adding rolling cache with item expiration for retrieving `ChannelOptions`.
Before:
```
BenchmarkContainer_ChannelOptions-12    	 8343092	       140.7 ns/op	      32 B/op	       1 allocs/op
BenchmarkContainer_Config-12            	23106529	        50.98 ns/op	       0 B/op	       0 allocs/op
```
After:
```
BenchmarkContainer_ChannelOptions-12    	22248208	        46.87 ns/op	       0 B/op	       0 allocs/op
BenchmarkContainer_Config-12            	54884310	        21.48 ns/op	       0 B/op	       0 allocs/op
```
=> Speed up channel config operations 

internal/middleware/user_header_auth.go, internal/middleware/user_header_auth_test.go, main.go
Possibility to set `client_user_id_http_header` option which contains a header name from which Centrifugo will try to extract authenticated user ID for client connections based on HTTP transports (all except unidirectional GRPC). This allows using proxies before Centrifugo which can authenticate requests and set user ID as a header.
In this case applications **must ensure that they strip such headers coming from clients on proxy level before authenticating request to avoid malicious usage**.
Ex.
```json
{
..
"client_user_id_http_header": "X-User-Id"
}
```
In this case we do not support setting  connection expiration and info.
TODO: possibly think a bit on a better option name.
=> Option to extract client connection user id from http header

.github/workflows/release.yml, .github/workflows/test.yml, CHANGELOG.md, misc/release/notes.md
Release notes and go version updates
=> Prepare v5.1.2 release

internal/tools/tls.go, internal/tools/tls_test.go, main.go
This PR adds tests for and refactors `tools.MakeTLSConfig` and then adds support for enabling mutual TLS authentication for Centrifugo servers by setting `ClientCAs` and `ClientAuth` in `tls.Config`.
=> Refactor MakeTLSConfig and support mTLS on server

.github/dependabot.yml
Use grouped dependabot version updates to reduce dependabot PR noise.
See
- https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
Here is a grouped PR from my repo as an example: https://github.com/j178/leetgo/pull/269
=> Use grouped dependabot version updates

main.go
Buggy behaviour (`--ttl` option did not work, default expiration was used):
```
./centrifugo gensubtoken --channel test --ttl 101010
HMAC SHA-256 JWT for anonymous user and channel "test" with expiration TTL 168h0m0s:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ey....[STRIPPED]
```
Fixed behaviour:
```
./centrifugo gensubtoken --channel test --ttl 101010
HMAC SHA-256 JWT for anonymous user and channel "test" with expiration TTL 28h3m30s:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ey....[STRIPPED]
```
=> Fix setting custom TTL in gensubtoken cli

go.mod, internal/sockjs/cancelctx.go, internal/sockjs/handler_sockjs.go, internal/sockjs/handler_sockjs_test.go, internal/sockjs/pool.go, internal/sockjs/pool_test.go, main.go
See #765 
The plan is:
* remove SockJS from `github.com/centrifugal/centrifuge` library - see https://github.com/centrifugal/centrifuge/pull/355
* move SockJS transport to Centrifugo (to support SockJS until Centrifugo v6) - this PR.
=> Move sockjs transport code to Centrifugo to start removing process

internal/rule/rule.go, internal/rule/rule_test.go, main.go
Relates #768 
Here we add validation of history ttl to be less or equal to configured history meta ttl. Otherwise meta information may expire before history stream which results into errors in runtime shown in related task.
=> Validate history ttl to be less or equal to history meta ttl

.github/workflows/release.yml, .github/workflows/test.yml, internal/apiproto/api.pb.go, internal/apiproto/api.proto, internal/consuming/postgresql_test.go, misc/release/notes.md
Add release notes, up Go to v1.22.1.
=> Prepare Centrifugo v5.3.0

internal/tools/config.go, internal/tools/duration.go, main.go
Fixes `unexpected end of JSON input` when unmarshalling slice of objects in YAML config. For example, the following config results into such error:
```yaml
namespaces:
- name: "test"
```
=> Fix unmarshaling slice of objects in yaml config

.github/workflows/test.yml
Switch to using the latest golangci-lint version. Verbose output may help diagnoze CI issues.
=> Up golangci-lint version, use verbose output

internal/consuming/kafka.go, internal/consuming/kafka_test.go
Pause processing partition to not block poll for a long time and not poll partition while it's being processed. This improves parallelism of partition processing and avoids theoretical stack of Kafka polling when parititon is processing message for a long time.
=> Kafka consumer: proper parallelism for partition processing

internal/consuming/kafka_test.go
Turned out there is a built-in `Partitioner` which uses partition from `Record`.
=> Use kgo.ManualPartitioner instead of custom one

internal/consuming/kafka.go, internal/consuming/kafka_test.go
Using channel buffer helps to avoid dropping messages already consumed from Kafka when rate inside partition is high enough. We still not blocking partition processing when buffer is full with the help of `default` branch in `select`.
=> Add partition buffer to optimize processing

main.go
Relates to #842 The approach is not to introduce a new command in client protocol but use RPC extension for the task. This makes all SDKs ready to be used automatically. The feature must be enabled in configuration:
```json
{
...
"rpc_ping": true,
"rpc_ping_method": "ping"
}
```
Then on SDK side:
```javascript
const startTime = performance.now();
centrifuge.rpc('ping', {}).then(function() {
const endTime = performance.now();
console.log('rtt', ((endTime - startTime)).toFixed(2).toString(), 'ms');  // Output example: rtt 0.90 ms
})
```
=> Add client rpc ping extension

main.go
Relates #865 
New Integer option `grpc_api_max_receive_message_size` if set to a value > 0 allows setting `grpc.MaxRecvMsgSize`. By default, GRPC library uses 4194304 bytes (4MB).
=> Add grpc_api_max_receive_message_size

main.go
Results into warning on start:
```
{"level":"warn","key":"CENTRIFUGO_DELTA_PUBLISH","time":"2024-10-06T08:48:22Z","message":"unknown key found in the environment"}
```
=> Add missing delta_publish top-level default

internal/tools/code_translate.go
Adjustment to #903, `to_response` is now just  `to`
=> Rename field in ConnectCodeToHTTPStatusTransform

internal/consuming/kafka.go, internal/consuming/kafka_test.go
There is a problem with current consuming - when under load and partition buffer channel is full the partition records fetched may be lost. Here we ensure we use proper offsets on next Poll for the partition in such a case using manual `SetOffsets` method.
Also, added tests for the problematic scenario, some internal refactoring and possibility to set `fetch_max_bytes` - the maximum number of bytes to fetch from Kafka in a single request.
=> Kafka: Fix potential loss of records under load

internal/consuming/kafka.go, internal/consuming/kafka_test.go
One more fix for Kafka consumer. The issue may lead to partition not being processed due to race in pause/resume. This was observed in production service under CPU throttling conditions. 
Also, a test case for this scenario.
=> Fix possible pause/resume race in Kafka consumer

Dockerfile
This PR updates the Dockerfile to improve security by running the application as a non-root user inside the container. This change ensures that the application no longer runs with root privileges, following best practices for containerized environments.
For more information, refer to the following resources:
* [Sysdig's Dockerfile Best Practices](https://sysdig.com/learn-cloud-native/dockerfile-best-practices/#1-1-rootless-containers)
* [Kubernetes Security Checklist](https://kubernetes.io/docs/concepts/security/security-checklist/#images)
=> Change Dockerfile to run app under non-root user

internal/proxy/refresh_handler_test.go
Fixes #910 
`expectedReply` is created before we start iterating over test cases, and the clock is ticking, so the server can respond in the next second. 
Before the change, it hit the issue 1-3 times in 1000 runs: 
```
$ go test ./internal/proxy -run TestHandleRefreshWithoutProxyServerStart -count 1000
--- FAIL: TestHandleRefreshWithoutProxyServerStart (0.00s)
refresh_handler_test.go:198: 
Error Trace:    /Users/amakhov/www/centrifugo/internal/proxy/refresh_handler_test.go:198
Error:          Not equal: 
expected: centrifuge.RefreshReply{Expired:false, ExpireAt:1733732303, Info:[]uint8(nil)}
actual  : centrifuge.RefreshReply{Expired:false, ExpireAt:1733732304, Info:[]uint8(nil)}
Diff:
--- Expected
+++ Actual
@@ -2,3 +2,3 @@
Expired: (bool) false,
- ExpireAt: (int64) 1733732303,
+ …
```
=> Fix flaky TestHandleRefreshWithoutProxyServerStart test

internal/app/run.go
If Centrifugo is built from source add a warning in case `version` is not set.
=> Add development build warning

internal/jwtverify/token_verifier_jwt.go, internal/jwtverify/token_verifier_jwt_test.go
Relates #961 
This should make the case with missing `alg` in Key Set work automatically. The only caveat is that theoretically the algorithm used by provider may differ from the one in token (but still in the same family - RSA or EC) – but this must be safe, the verification must always fail.
=> Handle jwks optional alg

docker-compose.yml, internal/configtypes/types.go, internal/consuming/aws_sqs_test.go, internal/consuming/kafka_test.go, internal/consuming/nats_jetstream.go, internal/consuming/nats_jetstream_test.go, internal/consuming/readme.md, internal/consuming/redis_stream_test.go
After the feedback from @matsuev some changes:
* turned out Nats Jetstream has new client - migrating to it
* for in-memory stream Nats consumer does not handle reconnections properly after Nats restart (it does this for ordered, but not for normal) – so upon getting heartbeat errors restarting the consumer now. So once stream appears – Centrifugo now resubscribes properly.
*  Nats 2.10 is minimal because it supports many subjects to filter
* StreamName is necessary for consumer now
* drop ordered consumer as messages are not load-balanced in that case
=> Nats JetStream consumer improvements

internal/configtypes/duration.go
Fixes error:
```
CENTRIFUGO_CHANNEL_NAMESPACES='[{"name":"test","history_size":1,"history_ttl":"300s","force_recovery":true,"force_recovery_mode":"cache"}]' centrifugo
{"level":"fatal","error":"error processing env: envconfig.Process: assigning CENTRIFUGO_CHANNEL_NAMESPACES to NAMESPACES: converting '[{\"name\":\"test\",\"history_size\":1,\"history_ttl\":\"300s\",\"force_recovery\":true,\"force_recovery_mode\":\"cache\"}]' to type configtypes.ChannelNamespaces. details: failed to unmarshal JSON array: json: cannot unmarshal string into Go struct field ChannelNamespace.ChannelOptions.history_ttl of type configtypes.Duration","time":"2025-04-16T11:42:15+02:00","message":"error getting config"}
```
=> Support unmarshaling of duration in env json

go.mod, internal/app/run.go, internal/jwks/manager_test.go
Starting from 1.24 Go can run crypto modules in FIPS 140-3 compatible mode. This can be controlled by GODEBUG, and we want to explicitly see that the mode is activated. See https://go.dev/doc/security/fips140
=> Log whether fips mode enabled on Centrifugo start

internal/cli/configdoc/schema.json, internal/configtypes/types.go, internal/consuming/postgresql.go, internal/consuming/postgresql_test.go
New option for PG consumer `use_try_lock` (boolean, default `false`) to use `pg_try_advisory_xact_lock` instead of `pg_advisory_xact_lock` for locking outbox table. This may help to reduce the number of long-running transactions on PG side.
=> Postgresql consumer: option to use try lock

internal/configtypes/types.go, internal/consuming/kafka.go, internal/consuming/kafka_test.go
This is a refactoring of Kafka consumer which aims to simplify the code and avoid SetOffsets call during poll loop.
We also tune fetch max wait time here to be 500ms instead of 5000ms since there is a chance that loaded partition may be paused until fetch returns (if no other partitions are active at this point - fetch blocks for up to 5 seconds).
With the changes made PR improves consumer throughput (according to added benchmark) in 3 times, having 30k msgs per seconds instead of 10k msgs per second (mostly due to fetch max wait time tuning).
New options:
* `fetch_max_wait` - duration, default 500ms
* `partition_queue_max_size` - int, default 1000
=> Kafka consumer: per-partition size-limited queue for backpressure, configurable fetch_max_wait

.github/dependabot.yml, go.mod, go.sum, internal/uniws/handler.go, internal/uniws/transport.go, internal/websocket/AUTHORS, internal/websocket/LICENSE, internal/websocket/README.md, internal/websocket/client.go, internal/websocket/client_server_test.go, internal/websocket/client_test.go, internal/websocket/compression.go, internal/websocket/compression_test.go, internal/websocket/conn.go, internal/websocket/conn_broadcast_test.go, internal/websocket/conn_test.go, internal/websocket/convert_safe.go, internal/websocket/convert_unsafe.go, internal/websocket/convert_unsafe_test.go, internal/websocket/doc.go, internal/websocket/mask.go, internal/websocket/mask_safe.go, internal/websocket/mask_test.go, internal/websocket/prepared.go, internal/websocket/prepared_test.go, internal/websocket/server.go, internal/websocket/server_test.go, internal/websocket/tls_handshake.go, internal/websocket/util.go, internal/websocket/util_test.go
Centrifuge library moved from `github.com/gorilla/websocket` to an internal fork quite a long time ago. But in Centrifugo we still depend on `github.com/gorilla/websocket` for unidirectional WebSocket.
I think it's better to depend on the same fork in Centrifugo also. For now using a raw copy of package into internal folder – to avoid maintaining a new public Go package.
Among being more maintained and avoiding a couple of issues in latest Gorilla WebSocket this change will provide a slightly optimized WebSocket Upgrades for unidirectional WebSocket.
Since all is internal – we can switch to a different approach later.
=> Copy websocket package from centrifuge

go.mod, go.sum, internal/app/engine.go, internal/app/run.go, internal/confighelpers/redis.go, internal/confighelpers/redis_test.go, internal/usage/usage.go
Relates #1008 
Now Redis mode should be logged correctly. Also, we now use a more detailed string for app-level sharding case which shows modes for all shards joined in a format like `engine_mode=sharded(2):cluster-x2` - which tells that app-level sharding is enabled with 2 shards in total and then each shard mode is described (joining consecutive same modes together).
=> Fix and improve redis mode logging

internal/cli/configdoc/schema.json, internal/configtypes/types.go, internal/consuming/kafka.go, internal/consuming/kafka_test.go
Fixes regression introduced in Centrifugo v6.2.3
Due to the fact we looked at number of items in queue instead of number of records memory usage could grow significantly since partitions were not paused much longer than required.
=> Fix memory leak in Kafka backpressure mechanism

internal/middleware/log.go, internal/wt/handler.go
A couple of fixes for WebTransport:
* at some point it stopped working when debug log level is used due to missing interface implementations in custom ResponseWriter
* suppress some errors which are not really interesting since happen in normal client closure cases.
=> WebTransport: make it work with debug middleware, suppress errors

internal/unihttpstream/handler_test.go, internal/unisse/handler.go, internal/unisse/handler_test.go, internal/uniws/config.go, internal/uniws/handler.go, internal/uniws/handler_test.go, internal/uniws/transport.go
This PR improves Centrifugo in the following ways:
* Support `cf_connect` URL param for unidirectional WebSocket, if set – there is no need to send the first connect message over WebSocket. This is similar to the existing `cf_connect` parameter [in uni SSE](https://centrifugal.dev/docs/transports/uni_sse#send-connect-request). The value is a URL-encoded JSON string which represents `ConnectRequest` object.
* Use protocol type for decoding `ConnectRequest` in uni ws case similar to uni sse and uni http stream, slightly reduces allocations
* Add tests for uni websocket, uni SSE, uni HTTP stream implementations
Relates #1032 
Example of using `cf_connect` (with `--client.insecure` flag on server side for demo purposes):
```
❯ wscat --connect …
```
=> cf_connect for unidirectional WebSocket, tests for uni transports
